### PR TITLE
Style books

### PR DESCRIPTION
**Pull request by olawale-o**
This pull request contains:
- An index.html file
- A style.css file
- A script.js file
- A linters.yml file
- HTML & CSS linters was used
## The following was implemented:
- Styling of the book list
- Stying of the add book form

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hello Team,

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._
- Use the exact webhint, stylelint, `.github/workflows/linters.yml` files in this [link](https://github.com/microverseinc/linters-config/tree/master/html-css).

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by olawale-o** [comment]
Hi @mikenath223 
We really appreciate you taking your time out to review our project, 
- we believe we followed all the requirements for this project because in microverse 2.0 we don't use development branch, for every approved PR we merge to main and create a new pull request from it for a new project you can check this [link] (https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) for more.
- for the linters we used the html,css and javascript linter provided in this link by micro verse [link](https://github.com/microverseinc/linters-config)

**Comment by mikenath223** [comment]
Hi, 
- Kindly disregard the Gitflow comment
- But use the exact linters in the HTML/CSS section: https://github.com/microverseinc/linters-config/tree/master/html-css

**Review by carlos-ssh — APPROVED** [review]
Hi @olawale-o & @toliboff, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
